### ISSUE TITLE
More packages for Linux

### ISSUE THREAD

**Issue by Jatin794** [LukeBriggsDev/Pepys#5]
Is something like more linux packages in the works? 

Anything would be preferable to flatpak (as it stands, the install takes me over 1GB for a journal app), though it'd be ideal if there were repo packages (PPA, AUR) or even installable files (deb, rpm, zst, tgz). Alternatively, snaps and appimages are also more efficient than flatpaks and thus more tolerable for being non-native packages.

The software looks great, but I'm afraid distributing it only via flatpak makes it too heavy for a markdown journal (about as heavy as native packages for libreoffice, firefox, emacs, obsidian and brave combined).

**Comment by LukeBriggsDev** [comment]
The flatpak was done first to maximise compatibility, but I understand that it makes the app incredibly large. 

I will work on more packages. A Fedora RPM is likely to be the first one to be completed. I will also make a .deb and an AUR package afterwards. It is unlikely that I will make any more than that.

In regards to other non-native packages, I will stick with just the flatpak as I don't see any reason to have multiple cross-distro packages. I believe Appimages are still dependent on system libraries and so can still cause compatibility issues on older distros, sort of defeating the point of cross distro. I didn't choose snaps because they are decompressed at runtime (this is why they can sometimes take a while to load) and the aforementioned size of this app when cross platform means it would take a while to load.

I will admit the size of the app is quite frustrating,  it is mainly due to the size of the qtwebengine which is a necessity for reasonable markdown rendering.

**Comment by LukeBriggsDev** [comment]
@Jatin794 I have created packages for Debian, Fedora 34, and Arch. They should be available in the [latest release](https://github.com/LukeBriggsDev/Pepys/releases/tag/v1.0.9). I have tested these and they should work correctly (but you can never really know until people start running it on their own machines)

Also thanks for showing interest in this project, it means a lot .

**Comment by Jatin794** [comment]
Yup, it's there. Can confirm it works as expected on Manjaro KDE that has many Qt libs installed.

It's a cool piece of software with reasonable defaults and an open format, so it really works when you want to get to journalling without making excuses
